version: '3'
services:
  rs-hello-world:
    hostname: rs-hello-world
    image: ccr.ccs.tencentyun.com/a2cd/rs-hello-world:latest
    container_name: rs-hello-world
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - HELLO=hello
    networks:
      - main

networks:
  main:
    external: true
