name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # pull代码
      - name: Build src
        run:  |
          cargo build --release --verbose
      - name: Run tests
        run: |
          cargo test --verbose
      - name: Build and push image
        env:
          IMAGE_TAG: 20240109
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_DOMAIN }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          echo "当前路径:"
          pwd
          echo "文件:"
          ls -l
          docker build -t ${{ secrets.REGISTRY_DOMAIN }}/a2cd/rs-hello-world:$IMAGE_TAG .
          docker push ${{ secrets.REGISTRY_DOMAIN }}/a2cd/rs-hello-world:$IMAGE_TAG
