name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # pull代码
      - name: Build src
        run:  |
          cargo build --release --verbose
      - name: Run tests
        run: |
          cargo test --verbose
      - name: Build and push image
        env:
          NAMESPACE: a2cd
          IMAGE_NAME: rs-hello-world
          IMAGE_TAG: 20240109
          RD: ${{ secrets.REGISTRY_DOMAIN }}
          RU: ${{ secrets.REGISTRY_USERNAME }}
          RP: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          echo $RP | docker login $RD -u $RU --password-stdin
          echo "当前路径:"
          pwd
          echo "文件:"
          ls -l
          docker build -t $RD/$NAMESPACE/$IMAGE_NAME:$IMAGE_TAG .
          docker push $RD/$NAMESPACE/$IMAGE_NAME:$IMAGE_TAG
